resources:
  - open-webui.yaml
  - ollama-service.yaml
  - ollama-statefulset.yaml
  - webui-deployment.yaml
  - webui-service.yaml
  - webui-pvc.yaml
  - tailscale-rbac.yaml
  - tailscale-serve-config.yaml
  - pipelines-pvc.yaml
  - pipelines-secret.yaml
  - pipelines-deployment.yaml
  - pipelines-service.yaml
