resources:
  - open-webui.yaml
  - ollama-service.yaml
  - ollama-statefulset.yaml
  - webui-deployment.yaml
  - webui-service.yaml
  - webui-ingress.yaml
  - webui-pvc.yaml
configMapGenerator:
- name: webui-host
  literals:
    - INGRESS_HOST=demo.tail2cdce7.ts.net 